spring.application.name=chat-app-backend

# MongoDB Atlas cloud connection
spring.data.mongodb.uri=mongodb+srv://pawanshigwan990_db_user:bcf9i3G2K5VoNWTw@cluster0.jbowwyu.mongodb.net/chatapp?retryWrites=true&w=majority&appName=Cluster0